import type { CSSProperties } from 'react';
import { UserRole, type User } from '../../types';
import StatusBadge from './StatusBadge';

interface UserListProps { users: User[]; isLoading?: boolean; busyUserId?: string | null; onEdit: (user: User) => void; onToggleStatus: (user: User) => void; }
const roles: Record<UserRole, string> = { [UserRole.ADMIN]: 'Administrador', [UserRole.SECRETARY]: 'Secretário', [UserRole.PASTOR]: 'Pastor' };

export default function UserList({ users, isLoading = false, busyUserId, onEdit, onToggleStatus }: UserListProps) {
  if (isLoading) return <p style={styles.muted}>Carregando usuários...</p>;
  if (users.length === 0) return <div style={styles.empty}><strong>Nenhum usuário cadastrado</strong><span>Crie o primeiro usuário usando o formulário.</span></div>;
  const sortedUsers = [...users].sort((a, b) => a.username.localeCompare(b.username, 'pt-BR'));
  return <div style={styles.tableWrap}><table style={styles.table}><thead><tr><th style={styles.cell}>Usuário</th><th style={styles.cell}>Perfil</th><th style={styles.cell}>Status</th><th style={{ ...styles.cell, textAlign: 'right' }}>Ações</th></tr></thead><tbody>{sortedUsers.map((user) => { const busy = busyUserId === user.id; return <tr key={user.id}><td style={styles.cell}><strong>{user.username}</strong>{user.isSuperAdmin && <span style={styles.superBadge}>Super</span>}</td><td style={styles.cell}>{roles[user.role]}</td><td style={styles.cell}><StatusBadge isActive={user.isActive} /></td><td style={{ ...styles.cell, textAlign: 'right' }}><div style={styles.actions}><button type="button" onClick={() => onEdit(user)} disabled={busy} style={styles.edit}>Editar</button><button type="button" onClick={() => onToggleStatus(user)} disabled={busy || user.isSuperAdmin} style={user.isActive ? styles.deactivate : styles.activate}>{busy ? 'Aguarde...' : user.isSuperAdmin ? 'Super protegido' : user.isActive ? 'Desativar' : 'Ativar'}</button></div></td></tr>; })}</tbody></table></div>;
}

const styles: Record<string, CSSProperties> = { tableWrap: { overflowX: 'auto', border: '1px solid #dce4e8', borderRadius: '14px', background: '#fff' }, table: { width: '100%', minWidth: '620px', borderCollapse: 'collapse', color: '#263742' }, cell: { padding: '15px 18px', borderBottom: '1px solid #edf0f2', textAlign: 'left', verticalAlign: 'middle' }, actions: { display: 'flex', justifyContent: 'flex-end', gap: '8px', flexWrap: 'wrap' }, edit: { padding: '7px 11px', border: '1px solid #ccd9df', borderRadius: '6px', background: '#fff', color: '#245a75', cursor: 'pointer' }, super: { padding: '7px 11px', border: 0, borderRadius: '6px', background: '#fff5d6', color: '#755b16', cursor: 'pointer' }, superBadge: { display: 'inline-block', marginLeft: '8px', padding: '3px 7px', borderRadius: '999px', background: '#fff5d6', color: '#755b16', fontSize: '.72rem', fontWeight: 800 }, activate: { padding: '7px 11px', border: 0, borderRadius: '6px', background: '#e8f6ef', color: '#17643b', cursor: 'pointer' }, deactivate: { padding: '7px 11px', border: 0, borderRadius: '6px', background: '#fff0f0', color: '#a32929', cursor: 'pointer' }, muted: { color: '#5c6670' }, empty: { display: 'grid', gap: '7px', padding: '34px', border: '1px dashed #cad6dc', borderRadius: '14px', color: '#53616c', textAlign: 'center' } };
